### ISSUE TITLE
ERROR: python compile.py ale

### ISSUE THREAD

**Issue by lucifer2859** [IGITUGraz/eligibility_propagation#3]
(eprop-figure) rlcube@rlcube:~/dchen/eligibility_propagation/Figure_4_and_5_ATARI$ python compile.py ale
- compiling using command: g++ -std=c++11 -shared ale.cc -o tfaleop.so -fPIC -I /home/rlcube/miniconda3/envs/eprop-figure/lib/python3.6/site-packages/tensorflow_core/include -O2 -D_GLIBCXX_USE_CXX11_ABI=1 -L/home/rlcube/miniconda3/envs/eprop-figure/lib/python3.6/site-packages/tensorflow_core -I/home/rlcube/miniconda3/envs/eprop-figure/lib/python3.6/site-packages/tensorflow_core/include -D_GLIBCXX_USE_CXX11_ABI=1 -L/home/rlcube/miniconda3/envs/eprop-figure/lib/python3.6/site-packages/tensorflow_core -l:libtensorflow_framework.so.1 -Iale/include -Lale/lib -lale
In file included from ale/include/ale/ale_interface.hpp:34,
                 from ale.cc:1:
ale/include/ale/emucore/OSystem.hxx:26:10: fatal error：emucore/Sound.hxx：No such file or directory
 #include "emucore/Sound.hxx"
          ^~~~~~~~~~~~~~~~~~~
Compilation interrupt.
Traceback (most recent call last):
  File "compile.py", line 19, in <module>
    res = sp.check_call(cmd, shell=True)
  File "/home/rlcube/miniconda3/envs/eprop-figure/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'g++ -std=c++11 -shared ale.cc -o tfaleop.so -fPIC -I /home/rlcube/miniconda3/envs/eprop-figure/lib/python3.6/site-packages/tensorflow_core/include -O2 -D_GLIBCXX_USE_CXX11_ABI=1 -L/home/rlcube/miniconda3/envs/eprop-figure/lib/python3.6/site-packages/tensorflow_core -I/home/rlcube/miniconda3/envs/eprop-figure/lib/python3.6/site-packages/tensorflow_core/include -D_GLIBCXX_USE_CXX11_ABI=1 -L/home/rlcube/miniconda3/envs/eprop-figure/lib/python3.6/site-packages/tensorflow_core -l:libtensorflow_framework.so.1 -Iale/include -Lale/lib -lale' returned non-zero exit status 1.

**Comment by franzscherr** [comment]
Could you try to checkout the commit `5e3c3c17be85c427802e529b432b8aad2e7fa82c` instead of the newest commit for the `Arcade-Learning-Environment` and try the procedure again?

**Comment by manar3333** [comment]
> Could you try to checkout the commit `5e3c3c17be85c427802e529b432b8aad2e7fa82c` instead of the newest commit for the `Arcade-Learning-Environment` and try the procedure again?

I checked out the this commit, then I got another error as shown below: 

- compiling using command: g++ -std=c++11 -shared ale.cc -o tfaleop.so -fPIC -I /home/user/anaconda3/envs/reward-based-E-PROP/lib/python3.7/site-packages/tensorflow/include -O2 -D_GLIBCXX_USE_CXX11_ABI=1 -L/home/user/anaconda3/envs/reward-based-E-PROP/lib/python3.7/site-packages/tensorflow -I/home/user/anaconda3/envs/reward-based-E-PROP/lib/python3.7/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1 -L/home/anaconda3/envs/reward-based-E-PROP/lib/python3.7/site-packages/tensorflow -l:libtensorflow_framework.so.1 -Iale/include -Lale/lib -lale
ale.cc:153:8: error: ‘ALEInterface’ in namespace ‘ale’ does not name a type
   ale::ALEInterface ale_;
        ^~~~~~~~~~~~
ale.cc:154:17: error: ‘Action’ is not a member of ‘ale’
   std::set<ale::Action> legalActions_;
                 ^~~~~~
ale.cc:154:17: note: suggested alternatives:
In file included from ale/include/ale/emucore/../common/display_screen.h:23,
                 from ale/include/ale/emucore/OSystem.hxx:40,
                 from ale/include/ale/ale_interface.hpp:34,
                 from ale.cc:1:
ale/include/ale/emucore/../common/Constants.h:28:6: note:   ‘Action’
 enum Action {
      ^~~~~~
In file included from /home/user/anaconda3/envs/reward-based-E-PROP/lib/python3.7/site-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/Core:139,
                 from /home/user/anaconda3/envs/reward-based-E-PROP/lib/python3.7/site-packages/tensorflow/include/unsupported/Eigen/CXX11/Tensor:14,
                 from /home/user/anaconda3/envs/reward-based-E-PROP/lib/python3.7/site-packages/tensorflow/include/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from /home/user/anaconda3/envs/reward-based-E-PROP/lib/python3.7/site-packages/tensorflow/include/tensorflow/core/framework/numeric_types.h:20,
                 from /home/user/anaconda3/envs/reward-based-E-PROP/lib/python3.7/site-packages/tensorflow/include/tensorflow/core/framework/allocator.h:26,
                 from /home/user/anaconda3/envs/reward-based-E-PROP/lib/python3.7/site-packages/tensorflow/include/tensorflow/core/framework/op_kernel.h:24,
                 from ale.cc:4:
/home/user/anaconda3/envs/reward-based-E-PROP/lib/python3.7/site-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/Constants.h:497:6: note:   ‘Eigen::Action’
 enum Action {GetAction, SetAction};


Could you please help with any suggestions?
